### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by jianxiashao** [jsfaint/auto-incognito#1]
![2024-10-21_200157](https://github.com/user-attachments/assets/d74bd860-b387-44ff-8058-6a646d552549)

**Comment by jsfaint** [comment]
之前的压缩包是从github页面直接下载的，但是直接下载不支持git lfs对象，所以icon.png就坏掉了。
已经重新提交了，0.4.1版已经修复了此问题。chrome已经审核通过了，edge估计还得几天……
